### ISSUE TITLE
Maintenance status?

### ISSUE THREAD

**Issue by soxofaan** [janikarh/enex2md#5]
hi @janik6n 

is enex2md still an active project for you?
I'm planning to do various tweaks (e.g. some Obsidian related finetuning, more fine-grained output tree control, ...) but I wonder if I should consider making PRs against your repo, or I just go my own way

**Comment by janik6n** [comment]
Thank you for reaching out @soxofaan. This project is  practically speaking in archive mode. I have migrated my data out of EN years ago, and do not really do Python any more. From your point of view: best to go forward with your own "forked" project. 

I would be interested to see how you will develop this little tool, so feel free to reply with link to this issue if you make your work public.

**Comment by soxofaan** [comment]
👍   I fully understand. 
That means I don't have to worry too much to partition my changes in orthogonal branches and atomic PRs  😄 

I already pushed some initial tweaks to my fork at https://github.com/soxofaan/enex2md

thanks publicly publishing your tool!

**Comment by psyciknz** [comment]
> 👍 I fully understand. That means I don't have to worry too much to partition my changes in orthogonal branches and atomic PRs 😄
> 
> I already pushed some initial tweaks to my fork at https://github.com/soxofaan/enex2md
> 
> thanks publicly publishing your tool!

@soxofaan Hi I found this project and thread yesteday (sorry you dont have issues opened or a way of messaging), but I was looking at exiting evernote for paperless.  So was going to add uploads to the paperless api into the code.  Keen to continue a discussion on your repo if you're up for it.  Expecially as I was hoping to export an entire notebook, and this fork and yours both fall over on parsing the enex_file.

**Comment by soxofaan** [comment]
Hi @psyciknz,

I enabled issues on my branch now (not sure why they were disabled, was not intended anyway). 
Note however that I don't envision a long term relationship with this tool. Probably like @janik6n  I guess: once I've tweaked it to cover my needs and I fully migrated away from Evernote, I'll probably lose interest in further development/maintenance.

**Comment by psyciknz** [comment]
Exactly as me.  I have actually found an Evernote_to_sqlite that was happy to open a full export of an evernote enex notebook (~500mb).  Where enex2md would not.   So have started adapting that for my purpose of uploading to paperless-ngx

**Comment by soxofaan** [comment]
@psyciknz FYI I've done some refactoring (currently in a feature branch https://github.com/soxofaan/enex2md/tree/parser) to, among other changes,  adapt the streaming XML parsing approach of Evernote_to_sqlite. This should make it possible to process larger  evernote exports than the original enex2md tool (which loads and processes all notes in memory as a whole)

**Comment by psyciknz** [comment]
Hi.

I've ended up getting what I needed from another project.  Happy to share it with you if you want (private repo at the moment).

I've been adding specifics for my migration from e denote to paperless.    There are a bunch I'd like to convert to md as well (notes rather than pdf files)
